### ISSUE TITLE
[INVALID] Better random number generator

### ISSUE THREAD

**Issue by sergeevabc** [hatsunearu/tc39#2]
Dear @hatsunearu, feel free to try [PCG][1]. It would be quite easy to adopt here.

[1]: http://www.pcg-random.org/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by hatsunearu** [comment]
Hi, sorry, this is a toy project to make sure I didn't go too long without writing some C. I am not maintaining it anymore, feel free to PR or fork if you want to use it for anything serious. 

I'll be monitoring PRs if you make any.

**Comment by sergeevabc** [comment]
Thank you for letting me know the project is abandoned.
Consider marking it as such on the front page.
